global:
    scrape_interval: 15s
    evaluation_interval: 15s

rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"

scrape_configs:
    # Prometheus itself
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']

    # Node Exporter - System metrics
    - job_name: 'node-exporter'
      static_configs:
          - targets: ['node-exporter:9100']
      scrape_interval: 5s
      metrics_path: /metrics

    # Nginx Exporter - Nginx metrics
    - job_name: 'nginx-exporter'
      static_configs:
          - targets: ['nginx-exporter:9113']
      scrape_interval: 5s
      metrics_path: /metrics

    # FastAPI Application - Custom metrics
    - job_name: 'grosint-backend'
      static_configs:
          - targets: ['host.docker.internal:8000']
      scrape_interval: 10s
      metrics_path: /metrics
      scrape_timeout: 5s

    # Nginx Status - Direct metrics
    - job_name: 'nginx-status'
      static_configs:
          - targets: ['host.docker.internal:80']
      scrape_interval: 10s
      metrics_path: /nginx_status
      scrape_timeout: 5s
