from __future__ import annotations

PHONE_LOOKUP_SPECS: dict[str, dict] = {
    "truecaller": {
        "source": "truecaller",
        "fields": [
            {"path": "name", "type": "name"},
            {"path": "birthday", "type": "birthday"},
            {"path": "gender", "type": "gender"},
            {"path": "image", "type": "image", "category": "IMAGE"},
            {"path": "phones[].carrier", "type": "carrier"},
            {"path": "phones[].type", "type": "phone_type"},
            {"path": "phones[].numberType", "type": "phone_type"},
            {"path": "addresses[]", "type": "address", "stringify": True},
            {"path": "internetAddresses[].id", "type": "email", "match": "email"},
            {"path": "internetAddresses[].id", "type": "internetAddress"},
            {"path": "badges[]", "type": "badge"},
        ],
    },
    "viewcaller": {
        "source": "viewcaller",
        "fields": [
            {"path": "name", "type": "name"},
            {"path": "names[].name", "type": "name"},
        ],
    },
    "eyecon": {
        "source": "eyecon",
        "fields": [
            {"path": "fullName", "type": "name"},
            {"path": "image", "type": "image", "category": "IMAGE"},
            {"path": "otherNames[].name", "type": "name"},
            {"path": "facebookID.url", "type": "facebook", "category": "LINK"},
            {"path": "facebookID.profileURL", "type": "image", "category": "IMAGE"},
        ],
    },
    "callapp": {
        "source": "callapp",
        "fields": [
            {"path": "name", "type": "name"},
        ],
    },
    "whatsapp": {
        "source": "whatsapp",
        "fields": [
            {
                "value": "Yes",
                "type": "whatsapp",
                "source": "Account Exist",
                "sourceOrType": "source",
            },
            {
                "paths": ["phone", "number"],
                "type": "whatsapp",
                "source": "Phone Number",
                "sourceOrType": "source",
                "first_only": True,
            },
            {
                "path": "countryCode",
                "type": "whatsapp",
                "source": "Country Code",
                "sourceOrType": "source",
            },
            {
                "path": "about",
                "type": "whatsapp",
                "source": "About",
                "sourceOrType": "source",
            },
            {
                "path": "aboutSetAt",
                "type": "whatsapp",
                "source": "About Set At",
                "sourceOrType": "source",
                "null_if": "1970-01-01T00:00:00.000Z",
            },
            {
                "path": "date",
                "type": "whatsapp",
                "source": "Last Seen",
                "sourceOrType": "source",
            },
            {
                "path": "id._serialized",
                "type": "whatsapp",
                "source": "WhatsApp ID",
                "sourceOrType": "source",
            },
            {
                "path": "profilePic",
                "type": "image",
                "category": "IMAGE",
                "when": {"path": "image_status", "not_equals": "not-authorized"},
            },
            {
                "path": "urlImage",
                "type": "image",
                "category": "IMAGE",
            },
            {
                "path": "isVerified",
                "type": "whatsapp",
                "source": "Verified",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "isBusiness",
                "type": "whatsapp",
                "source": "Business Account",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "isUser",
                "type": "whatsapp",
                "source": "Is User",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "isWAContact",
                "type": "whatsapp",
                "source": "Is WhatsApp Contact",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "isBlocked",
                "type": "whatsapp",
                "source": "Is Blocked",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "businessProfile.address",
                "type": "whatsapp",
                "source": "Address",
                "sourceOrType": "source",
                "when": {"path": "isBusiness", "equals": True},
            },
            {
                "path": "businessProfile.description",
                "type": "whatsapp",
                "source": "Description",
                "sourceOrType": "source",
                "when": {"path": "isBusiness", "equals": True},
            },
            {
                "path": "businessProfile.email",
                "type": "whatsapp",
                "source": "Email",
                "sourceOrType": "source",
                "when": {"path": "isBusiness", "equals": True},
            },
            {
                "path": "businessProfile.website[].url",
                "type": "whatsapp",
                "source": "Website",
                "sourceOrType": "source",
                "when": {"path": "isBusiness", "equals": True},
            },
            {
                "path": "businessProfile.categories[].localized_display_name",
                "type": "whatsapp",
                "source": "Category",
                "sourceOrType": "source",
                "when": {"path": "isBusiness", "equals": True},
            },
            {
                "path": "businessProfile.businessHours.timezone",
                "type": "whatsapp",
                "source": "Business Timezone",
                "sourceOrType": "source",
                "when": {"path": "isBusiness", "equals": True},
            },
            {
                "path": "businessProfile.memberSinceText",
                "type": "whatsapp",
                "source": "Member Since",
                "sourceOrType": "source",
                "when": {"path": "isBusiness", "equals": True},
            },
            {
                "path": "isEnterprise",
                "type": "whatsapp",
                "source": "Enterprise Account",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "faceAnalysis.description",
                "type": "whatsapp",
                "source": "Image Description",
                "sourceOrType": "source",
            },
            {
                "path": "faceAnalysis.tags[]",
                "type": "whatsapp",
                "source": "Image Tag",
                "sourceOrType": "source",
            },
            {
                "path": "checkMetadata.email",
                "type": "whatsapp",
                "source": "Check Email",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "checkMetadata.device",
                "type": "whatsapp",
                "source": "Check Device",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "checkMetadata.possibleMigration",
                "type": "whatsapp",
                "source": "Possible Migration",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "checkMetadata.isBanned",
                "type": "whatsapp",
                "source": "Is Banned",
                "sourceOrType": "source",
                "transform": "yes_no",
            },
            {
                "path": "fbLeak.message",
                "type": "whatsapp",
                "source": "FB Leak",
                "sourceOrType": "source",
            },
            {
                "path": "fbLeak.error",
                "type": "whatsapp",
                "source": "FB Leak Error",
                "sourceOrType": "source",
            },
            {
                "path": "aboutHistory[].about",
                "type": "whatsapp",
                "source": "About History",
                "showSource": True,
            },
            {
                "path": "aboutHistory[].aboutSetAt",
                "type": "whatsapp",
                "source": "About History Set At",
                "showSource": True,
            },
        ],
    },
}
